### ISSUE TITLE
import ol-cesium

### ISSUE THREAD

**Issue by sowston** [openlayers/ol-cesium#456]
I would like to be able to easily import ol-cesium into a vue component as an ES6 module and cannot seem to get this working in any convention (require, webpack loaders, etc)

I would like to simply use:

import Cesium from 'cesium'
import olcs from 'ol-cesium'

Two questions:
1.  Can you provide a timeline of when ol-cesium will be supported as an ES6 module?
2.  If 1 above is quite a ways out, is there any examples anywhere of how to get ol-cesium working in vue?  

Thank you!

**Comment by gberaudo** [comment]
There is no such possibility yet. There is no timeline, it all depends on community involvement..
Here are the expected steps to reach this goal:
- migrate to `goog.module`;
- add a transform target based on https://github.com/gberaudo/googshift.

I don't know about vue, maybe someone from the community have experience with it and the closure compiler? Please share here your findings.

**Comment by anste** [comment]
Should it be possible to use olcs already?
I tried to use the package like stated on [https://www.npmjs.com/package/olcs](https://www.npmjs.com/package/olcs) but I always get 

> Module not found: Error: Can't resolve 'goog/asserts'

Am I missing something?

**Comment by EduardoNogueira** [comment]
^ Same here. Anyone know how to fix this?

**Comment by gberaudo** [comment]
@anste and @EduardoNogueira, I missed your messages.

You need to have a file like this somewhere (goog/asserts.js):
```
export default {
  assert(condition) {
    console.assert(condition);
  },
  assertInstanceof(object, type) {
    console.assert(object instanceof type);
  },
  fail() {
    console.fail();
  },
  assertNumber(number) {
    console.assert(typeof number === 'number');
  }
}
```

If you are using webpack you can configure an 'alias' to point the 'goog' namespace to the directory containing that file. Could you try?

**Comment by gberaudo** [comment]
@anste and @EduardoNogueira, I created #563 and released version 0.0.4 of the olcs package. Let me know the result of our experiments.

**Comment by anste** [comment]
@gberaudo thankt you for your reply. I tried your new version, but I still have problems. Several imports in different files contain duplicate file endings (e.g. "import olcsUtil from './util.js.js';" in "OLCesium.js") leading to errors while bundling.

**Comment by gberaudo** [comment]
Right @anste. I created https://github.com/openlayers/ol-cesium/pull/565 to fix this. I will publish a new version in a moment.

**Comment by anste** [comment]
Ok, now I get:
```
ERROR in ./node_modules/olcs/OverlaySynchronizer.js
Module not found: Error: Can't resolve 'ol.js'
```
Is it correct, that still ol 4.5.0 is used in this Project, while olcesium uses openlayers 4.6.4?

**Comment by gberaudo** [comment]
No that is not correct, I am fixing it and the issue with `ol.js`.

**Comment by gberaudo** [comment]
@anste, I fixed many issues with the olcs package. Could you please test again with the latest version?

**Comment by anste** [comment]
@gberaudo, I still get warnings and errors. I think some of the ol imports are wrong. E.g. AbstractSynchronizer:

`import * as olBase from 'ol/index.js';`

Each module in ol has one single default export ([see ol description](https://www.npmjs.com/package/ol#module-identifiers)). So you should never need a star import. I think the correct way would be:
`import ol from 'ol/index.js';`
or shorter in that case:
`import ol from 'ol';`

**Comment by gberaudo** [comment]
Yes @anste, you are right.

Unfortunately the `ol` package is quite outdated (3 months old now)  and `openlayers` master is diverging more and more from it everyday. So it is not reasonable to base on it.

Notably, as you discovered, OpenLayers has decided to switch to named exports for namespaces and it impacts us.

For my tests, I am using openlayers bfae19c7e138533ad0c1a071d8886d55aac9bd35 from February 23rd, which looks like a good compromise:
- not too old -> close to the final OpenLayers API;
- not too recent -> less breaking changes from OL5.

You can base on that version by setting in your `package.json`:
`'openlayers: 'https://api.github.com/repos/openlayers/openlayers/tarball/bfae19c7e138533ad0c1a071d8886d55aac9bd35'`

and by defining a webpack alias: `'ol': 'openlayers/src/ol'`.

I published a new version, which I tested using `https://github.com/camptocamp/ngeo/blob/master/examples/simple3d.html`.

@ahocevar, what is the plan regarding the `ol` package? Should people stop using it now and base on OpenLayers master?

**Comment by ahocevar** [comment]
@gberaudo The best option currently is using an ol beta (the latest at the moment of writing is `5.0.0-beta.8`).

Later this week, we'll also provide a jscodeshift transform that converts most v4.6.x imports to v5.0.x imports automatially.

**Comment by anste** [comment]
@gberaudo I didn't notice that there were breaking changes since 4.6.4. Thank you for your explanation. I think I will wait for openlayers 5.0.0 and test ol-cesium again.

**Comment by gberaudo** [comment]
Thanks @ahocevar for the information. That jscodeshift transform will certainly be quite interesting code, I am looking forward to it.

Thanks @anste for your tests and see you again when the situation has stabilized.

**Comment by gberaudo** [comment]
OL-Cesium 2.0 was released as ES6 module.
