### ISSUE TITLE
Examples does not work

### ISSUE THREAD

**Issue by 1Map** [openlayers/ol-cesium#585]
https://openlayers.org/ol-cesium/examples/

Examples does not work.  Gives error messages:

![image](https://user-images.githubusercontent.com/1152458/39672120-5deec5d4-5124-11e8-8004-66a04eba2b83.png)

**Comment by gberaudo** [comment]
Thanks @1Map for reporting the issue. I just published a fix for it.

**Comment by 1Map** [comment]
Still getting javascript error on:
https://openlayers.org/ol-cesium/examples/selection.html

**Comment by gberaudo** [comment]
Right, thanks, it is now be fixed.

**Comment by 1Map** [comment]
Not fixed

**Comment by gberaudo** [comment]
@1Map, it should now be fixed. Thanks for your comment.

**Comment by 1Map** [comment]
@gberaudo Thanks.  It still gives a 403 error at:
https://assets.agi.com/stk-terrain/world/layer.json

The example I am looking at is:
https://openlayers.org/ol-cesium/examples/sidebyside.html

**Comment by gberaudo** [comment]
Indeed, I republished the examples and now the correct version of Cesium is used.

**Comment by 1Map** [comment]
@gberaudo  Thanks, it is working now.  Just one more question.  Why is cesium much darker in color?

![image](https://user-images.githubusercontent.com/1152458/54376614-1e589b80-468c-11e9-8979-26e9d6b1bdcd.png)

**Comment by gberaudo** [comment]
@1Map, this is due to the HDR capability the Cesium team added in Cesium 1.52.

Here is the relevant line from their CHANGELOG.md:
* Added support for high dynamic range rendering. It is enabled by default when supported, but can be disabled with `Scene.highDynamicRange`. [#7017](https://github.com/AnalyticalGraphicsInc/cesium/pull/7017)

It is indeed quite disturbing in side-by-side mode. Would you want to contribute a PR that disables `scene.highDynamicRange` in that example?
